package rules

import com.fly.drools.entity.RuleResult
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.context.ApplicationContext
import java.util.List
import com.fly.drools.test.TestService
import com.fly.drools.test.TestParam

rule "discount_rule_4"
    when
        p: TestParam()
        r: RuleResult()
        log: Logger()
        context: ApplicationContext()
        testService: TestService()
    then
        log.info("drools execute...");

        List<String> list = testService.getList();

        if (list.contains(p.getName())) {
            testService.insertParam(p);
            r.setData(200);
        }

        TestService t = context.getBean(TestService.class);
        String res = t.test("123456");
        r.setData(100);
        log.info("test spring context: {}", res);
end