package rules

import com.fly.drools.entity.RuleResult
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.context.ApplicationContext
import com.fly.drools.test.TestService
import java.util.Map

declare Param
    age: int
    name: String
    degree: String
end

rule "discount_rule_4"
    when
        p: Map()
        param: Param()
        r: RuleResult()
        log: Logger()
        context: ApplicationContext()
    then
        log.info("drools execute, map={}", p);
        log.info("drools execute, param={}", param);

        TestService t = context.getBean(TestService.class);
        String res = t.test("123456");
        r.setData("hello world");
        log.info("test spring context: {}", res);
end